name: Continuous Integration

on: 
  push:
    branches:
      - "main"

jobs:
  continous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Run install
        uses: borales/actions-yarn@v4

      - name: run install, build and test
        run: 
          yarn install
          yarn build
          yarn test